# Generated by Django 4.0.5 on 2022-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_dressingroom_alter_movie_actors_actor_dressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressingroom',
            name='floor',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
